---
language: java
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8
before_script:
- psql -c 'create database nutztest;' -U postgres
- cp ./tools/travis-ci/nutz-test.properties ./test/
- cp ./tools/travis-ci/log4j.properties ./test/
before_install:
- export TZ=Asia/Shanghai
env:
  global:
  - secure: E1z+6z9M4iTdAXZ2a1rYSrxfIOq6PkdXEMutAbIn/bp1e/Qvb5IVoAS0heo7SPwcIlHlN8mDiOtKdzbcu9q8VaftfHwFjff6AoKyuWtfDqE1ecTfflebWwzmtXKJmT5uxBPvu442dS4sIc2zx3zjvnxMsSmvrdSwbMxwdbAKvDc=
addons:
  coverity_scan:
    project:
      name: nutzam/nutz
      description: Build submitted via Travis CI
    notification_email: wendal1985@gmail.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
