---
language: java
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8
before_script:
- psql -c 'create database nutztest;' -U postgres
- cp ./tools/travis-ci/nutz-test.properties ./test/
- cp ./tools/travis-ci/log4j.properties ./test/
before_install:
- export TZ=Asia/Shanghai
